name: Lint
description: Runs Ruff to lint and format

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies with uv
      shell: bash -l {0}
      run: uv sync

    - name: Dry-run formatter check
      shell: bash -l {0}
      run: ruff format --check .

    - name: Run linter
      shell: bash -l {0}
      run: ruff check .
